# This is a basic workflow to help you get started with Actions

name: EPG & Playlist.json

# Controls when the workflow will run
on:
  schedule:
  # Runs "at minute 55 past every hour" (see https://crontab.guru)
  - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # Runs a set of commands using the runners shell
      - name: Run Build Envsetup
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip python3 git neofetch
          python -m pip install --upgrade pip
          neofetch
          git clone https://github.com/akmalharith/epg-grabber ~/epg_grabber
          echo ::add-path::$HOME/.local/bin

      - name: Install tox and any other packages
        run: pip install git+https://github.com/akmalharith/epg-grabber.git
          
      - name: Start grabbing EPG
        run: |
          cd altostv
          python3 ambilepg.py
          python3 gantiidepg.py
          
      - name: Push xml
        run: |
          mkdir ~/Dump-epg
          cp altostv/tv.xml .
          git config --global user.name "AltosTVRBot"
          git config --global user.email "TestBot@example.org"
          git config --global user.password "${{ secrets.PA_TOKEN }}"
          git init
          git add *
          git commit -m "Automatically Update EPG && Playlist"
          git branch -M dump-epg
          git remote add origin  https://ibraaltabian17:${{ secrets.PA_TOKEN }}@github.com/ibraaltabian17/DumperYeshA.git
          git push -u origin dump-epg -f

          
          
