# This is a basic workflow to help you get started with Actions

name: EPG

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run Build Envsetup
        run: |
          sudo apt-get -y install python3-pip git
          git clone https://github.com/akmalharith/epg-grabber.git ~/epg-grabber
          cd ~/epg-grabber
          pip3 install -r requirements.txt
          
      - name: Start grabbing
        run: |
          export CONFIG_URL=https://raw.githubusercontent.com/akmalharith/epg-grabber/main/epg_grabber/sites/channels_config/visionplus_channels.txt
          cd ~/epg-grabber/epg_grabber
          python3 -u app.py
